---
version: '2.4'

services:
  wiremock:
    container_name: wiremock
    image: rodolpheche/wiremock
    volumes:
      - ./../mocks/wiremock:/home/wiremock:rw
    ports:
      - 8765:8080
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
